import mongoose from 'mongoose';

const EtsyOrderFulfilmentSchema = new mongoose.Schema({
  store: { type: mongoose.Schema.Types.ObjectId, ref: 'EtsyStore', index: true },
  dateSold: { type: String, default: '' },
  etsyOrdersReceivedTime: { type: String, default: '' },
  shipBy: { type: String, default: '' },
  estimateEtsyDelivery: { type: String, default: '' },
  productName: { type: String, default: '' },
  sku: { type: String, default: '' },
  address: { type: String, default: '' },
  zipCode: { type: String, default: '' },
  region: { type: String, default: '' },
  qty: { type: String, default: '' },
  note: { type: String, default: '' },
  messageUpdate: { type: String, default: '' },
  soldFor: { type: String, default: '' },
  tax: { type: String, default: '' },
  total: { type: String, default: '' },
  etsyFee: { type: String, default: '' },
  processingFee: { type: String, default: '' },
  regulatoryOperatingFee: { type: String, default: '' },
  tds: { type: String, default: '' },
  tcs: { type: String, default: '' },
  offsiteAds: { type: String, default: '' },
  coupons: { type: String, default: '' },
  relistFee: { type: String, default: '' },
  tId: { type: String, default: '' },
  net: { type: String, default: '' },
  estimateAmazonDelivery: { type: String, default: '' },
  amazonAccount: { type: String, default: '' },
  cardNo: { type: String, default: '' },
  itemCost: { type: String, default: '' },
  shipCost: { type: String, default: '' },
  amazonTax: { type: String, default: '' },
  totalInUsd: { type: String, default: '' },
  totalInRs: { type: String, default: '' },
  markUpFee: { type: String, default: '' },
  igst: { type: String, default: '' },
  amazonTotal: { type: String, default: '' },
  exRate: { type: String, default: '' },
  inHand: { type: String, default: '' },
  issuesIfAny: { type: String, default: '' },
  trackingId: { type: String, default: '' },
  remark: { type: String, default: '' },
  trackingIdUploaded: { type: String, default: '' },
  amazonOrderNumber: { type: String, default: '' },
  orderStatus: { type: String, default: '' },
  refund: { type: String, default: '' },
  rowOrder: { type: Number, default: 0, index: true },
}, { timestamps: true });

EtsyOrderFulfilmentSchema.index({ store: 1, rowOrder: 1 });

export default mongoose.model('EtsyOrderFulfilment', EtsyOrderFulfilmentSchema);
